version: "3"
services:
  hub:
    image: selenium/hub:4.15.0
  chrome:
    image: selenium/node-chrome:4.15.0
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
      replicas: 1
    env_file: .env
  firefox:
    image: selenium/node-firefox:4.15.0
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
      replicas: 0
    env_file: .env